# Pass an immutable Fedora base reference and its expected release.
ARG BASE_IMAGE
FROM ${BASE_IMAGE}
ARG BASE_IMAGE
ARG FEDORA_RELEASE

RUN printf '%s\n' "$BASE_IMAGE" | grep -Eq '^registry\.fedoraproject\.org/fedora@sha256:[0-9a-f]{64}$' \
    && test -n "$FEDORA_RELEASE" \
    && . /etc/os-release \
    && test "$ID" = fedora && test "$VERSION_ID" = "$FEDORA_RELEASE" \
    && dnf -y --setopt=install_weak_deps=False install \
    gcc make bc bison flex openssl-devel elfutils-libelf-devel dwarves \
    ncurses-devel perl python3 python3-gobject-base openssl util-linux cpio kmod dracut grub2-efi-x64-modules \
    grub2-tools grub2-tools-extra gdisk dosfstools mtools e2fsprogs parted \
    rpm rpm-build redhat-rpm-config kernel-rpm-macros python3-rpm-macros python3-jsonschema python3-pyyaml \
    rpm-ostree ostree createrepo_c gnupg2 dnf5 git xz ca-certificates binutils python3-virt-firmware qemu-system-x86-core qemu-img edk2-ovmf \
    && dnf clean all \
    && printf 'quirkbench-fedora-rootless-build-v1\n' > /etc/quirkbench-container \
    && printf '%s\n' "${BASE_IMAGE##*@}" > /etc/quirkbench-base-digest
WORKDIR /workspace
