"""Investigation command arguments; services own behavior and authorization."""
from pathlib import Path
from .cli_parser import action


def build(root):
    p = action(root, 'investigation start', 'Start an investigation for one target and problem', command='investigation', internal_action='start')
    p.add_argument('name', help='stable investigation identity')
    p.add_argument('--request-id', help='original durable retry identity; recorded for retries')
    p.add_argument('--target', required=True, help='existing enrolled and registered target')
    p.add_argument('--problem', type=Path, help='bounded UTF-8 problem description')
    p.add_argument('--workspace', help='reserved source workspace identity')
    p.add_argument('--baseline', help='explicit supported baseline ID when catalog selection is ambiguous')
    p.add_argument('--session-seconds', type=int, default=28800, help='Investigation time budget in seconds')
    p.add_argument('--token-budget', type=int, default=1000000, help='Recorded agent token budget for this investigation')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation brief', 'Get an agent handoff and the next useful commands', command='investigation', internal_action='brief')
    p.add_argument('name', help='stable investigation identity')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation status', 'Show preparation, experiments and actions needing attention', command='investigation', internal_action='status')
    p.add_argument('name', help='existing investigation name')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation pause', 'Stop admitting new work; let active workers drain', command='investigation', internal_action='pause')
    p.add_argument('name', help='existing investigation name')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation resume', 'Resume a paused investigation after reconciliation', command='investigation', internal_action='resume')
    p.add_argument('name', help='existing investigation name')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation context', 'Read source, evidence and the current investigation context', command='investigation', internal_action='context')
    p.add_argument('name', help='existing investigation identity')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation history', 'Read recorded runs, events or evidence', command='investigation', internal_action='history')
    p.add_argument('name', help='existing investigation identity')
    p.add_argument('--after', type=int, default=0, help='cursor for this investigation and query kind')
    p.add_argument('--limit', type=int, default=20, help='Maximum records to return')
    p.add_argument('--kind', choices=('attempts', 'events', 'evidence'), default='attempts', help='Which recorded history category to list')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation source prepare', 'Prepare the pinned distribution source workspace', command='investigation', internal_action='prepare-distribution')
    p.description += '\nUsually use experiment submit to coordinate all preparation stages.'
    p.add_argument('name', help='stable investigation identity')
    p.add_argument('--request-id', help='original durable retry identity; recorded for retries')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation source show', 'Inspect the source workspace and writer handoff', command='investigation', internal_action='source')
    p.add_argument('name', help='existing investigation name')
    p.add_argument('--workspace', help='exact workspace; inferred only when unique')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation source capture', 'Capture exact source after writers have stopped', command='investigation', internal_action='capture-source')
    p.description += '\nUsually use experiment submit to coordinate all preparation stages.'
    p.add_argument('name', help='existing investigation name')
    p.add_argument('--workspace', help='exact workspace; inferred only when unique')
    p.add_argument('--request-id', help='durable retry identity; required for each capture and JSON preparation')
    p.add_argument('--quiesced', action='store_true', help='explicitly acknowledge all source writers have stopped')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation source release', 'Release a completed capture handoff for editing', command='investigation', internal_action='release-source')
    p.add_argument('name', help='existing investigation name')
    p.add_argument('--workspace', help='exact workspace; inferred only when unique')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation build prepare', 'Prepare the candidate filesystem for a diagnostic build', command='investigation', internal_action='prepare-candidate')
    p.description += '\nUsually use experiment submit to coordinate all preparation stages.'
    p.add_argument('name', help='existing investigation identity')
    p.add_argument('--request-id', required=True, help='stable identity for exact replay; use a new identity after failed work')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation build kernel', 'Build captured source using a prepared candidate filesystem', command='investigation', internal_action='build')
    p.description += '\nUsually use experiment submit to coordinate all preparation stages.'
    p.add_argument('name', help='existing investigation identity')
    p.add_argument('--request-id', required=True, help='stable identity for exact replay; use a new identity after failed work')
    p.add_argument('--capture', required=True, help='completed source capture operation ID')
    p.add_argument('--candidate', required=True, help='completed candidate preparation operation ID')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation build system', 'Assemble and sign a system from completed build outputs', command='investigation', internal_action='compose')
    p.description += '\nUsually use experiment submit to coordinate all preparation stages.'
    p.add_argument('name', help='existing investigation identity')
    p.add_argument('--request-id', required=True, help='stable identity for exact replay; use a new identity after failed work')
    p.add_argument('--build', required=True, help='completed joined build operation ID')
    p.add_argument('--repository', required=True, help='configured controller repository alias and signing policy')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation baseline show', 'Show the selected unmodified baseline and missing inputs', command='investigation', internal_action='baseline')
    p.add_argument('name', help='stable investigation identity')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation baseline prepare', 'Prepare the pinned unmodified distribution source', command='investigation', internal_action='prepare-distribution')
    p.description += '\nUsually use experiment submit to coordinate all preparation stages.'
    p.add_argument('name', help='stable investigation identity')
    p.add_argument('--request-id', help='original durable retry identity; recorded for retries')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation proposal schema', 'Show the proposal input schema and current source context', command='investigation', internal_action='proposal-schema')
    p.add_argument('name', help='existing investigation identity')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation proposal add', 'Record a recommendation, observation request or conclusion', command='investigation', internal_action='propose')
    p.add_argument('name', help='Investigation name')
    p.add_argument('--file', type=Path, required=True, help='Path to the JSON input file')
    p.add_argument('--request-id', required=True, help='Durable request identity for safe retries')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation proposal list', 'List recorded proposals and their preparation', command='investigation', internal_action='proposals')
    p.add_argument('name', help='Investigation name')
    p.add_argument('--after', type=int, default=0, help='Continue after the returned cursor')
    p.add_argument('--limit', type=int, default=20, help='Maximum records to return')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation proposal submit', 'Submit a recorded proposal with explicit build and publication choices', command='investigation', internal_action='dispatch-proposal')
    p.add_argument('name', help='Investigation name')
    p.add_argument('--proposal', required=True, help='Recorded proposal operation ID')
    p.add_argument('--candidate', help='Completed candidate preparation ID')
    p.add_argument('--repository', help='Configured repository alias')
    p.add_argument('--request-id', help='Durable request identity for safe retries')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation recipe list', 'List reviewed test recipes for this investigation', command='investigation', internal_action='recipes')
    p.add_argument('name', help='existing investigation identity')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation observation list', 'List requests for human observations', command='investigation', internal_action='observations')
    p.add_argument('name', help='existing investigation identity')
    p.add_argument('--after', type=int, default=0, help='cursor for this investigation and query kind')
    p.add_argument('--limit', type=int, default=20, help='Maximum records to return')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation observation show', 'Read one observation request and its answer', command='investigation', internal_action='observation')
    p.add_argument('name', help='existing investigation identity')
    p.add_argument('--request', required=True, help='Observation request ID')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation observation answer', 'Answer a request using a typed observation file', command='investigation', internal_action='respond')
    p.add_argument('name', help='existing investigation identity')
    p.add_argument('--request', help='Observation request ID', required=True)
    p.add_argument('--file', type=Path, help='JSON observation response matching the requested question', required=True)
    p.add_argument('--request-id', required=True, help='durable answer retry identity')
    p.set_defaults(operator=None)
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation results show', 'Compare recorded outcomes without assuming reproduction or a fix', command='investigation', internal_action='report')
    p.add_argument('name', help='Investigation name')
    p.add_argument('--comparison', type=Path, help='versioned declarations mapping exact experiments to comparison roles')
    p.add_argument('--after', type=int, default=0, help='Continue after the returned cursor')
    p.add_argument('--limit', type=int, default=5, help='Maximum records to return')
    p.add_argument('--experiment', help='select one exact experiment in this investigation')
    p.add_argument('--attempt-after', type=int, default=0, help='Continue target runs after this returned cursor')
    p.add_argument('--attempt-limit', type=int, default=5, help='Maximum target runs per experiment')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation results retain', 'Keep the currently recorded results and supporting evidence', command='investigation', internal_action='report-retain')
    p.add_argument('--request-id', help='durable retry identity, new ID for a later selection')
    p.add_argument('name', help='Investigation name')
    p.add_argument('--note', required=True, help='Reason for this action, retained with its record')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation results export', 'Export patches, report and evidence to a new archive', command='investigation', internal_action='export')
    p.add_argument('name', help='Investigation name')
    p.add_argument('--output', type=Path, required=True, help='New output path; existing files are not overwritten')
    p.add_argument('--capture', help='completed stopped source capture operation; default current handed-off capture')
    p.add_argument('--author', help='explicit Name <email> for an export representation of dirty captured changes')
    p.add_argument('--comparison', type=Path, help='Path to explicit baseline/candidate comparison JSON')
    p.add_argument('--timeout', type=int, default=300, help='Maximum operation duration in seconds')
    p.add_argument('--reserve-gib', type=float, default=20, help='Free storage reserve in GiB')
    p = action(root, 'investigation evidence read', 'Read a bounded range of public investigation evidence', command='evidence', internal_action='read')
    p.add_argument('digest', help='SHA256 of the authorized output listed by the related record')
    p.add_argument('--offset', type=int, default=0, help='Starting byte offset for this read')
    p.add_argument('--length', type=int, default=16384, help='Maximum bytes to read (at most 16384)')
    p.add_argument('--after', type=int, default=0, help='Continue after the returned cursor')
    p.add_argument('--limit', type=int, default=20, help='Maximum records to return')
    p.add_argument('name', help='Investigation name')
