"""Dev command arguments; services own behavior and authorization."""
from pathlib import Path
from .cli_parser import action


def build(root):
    p = action(root, 'dev install', 'Install an unsigned development archive; activation requires stopped work', command='controller-install', internal_action=None)
    p.add_argument('archive', nargs='?', type=Path, help='Path to the original unsigned controller archive')
    p.add_argument('--activate', action='store_true', help='Switch CLI and worker paths together after stopped-work checks')
    p.add_argument('--rollback', action='store_true', help='Restore the previous runtime from the recorded activation')
    p.add_argument('--release-statement', type=Path, help='Path to the signed release statement JSON')
    p.add_argument('--release-signature', type=Path, help='Path to the detached release statement signature')
    p.add_argument('--release-key', type=Path, help='independently trusted publisher public key')
    p.add_argument('--release-fingerprint', help='full independently trusted publisher fingerprint')
    p.add_argument('--release-recovery', type=Path, help='Recovery archive matching the signed release')
    p.add_argument('--release-builder', type=Path, help='Builder archive matching the signed release')
    p.add_argument('--release-catalog', type=Path, help='Baseline catalog matching the signed release')
    p.add_argument('--release-recovery-manifest', type=Path, help='Recovery manifest matching the signed release')
    p.add_argument('--release-recovery-candidate', type=Path, help='Recovery candidate record matching the signed release')
    p = action(root, 'dev recovery plan', 'Plan exact package downloads from an immutable input specification', command='recovery-bundle', internal_action='plan')
    p.add_argument('--spec', type=Path, required=True, help='Path to an immutable candidate specification JSON file')
    p.add_argument('--output', type=Path, required=True, help='New output path; existing files are not overwritten')
    p = action(root, 'dev recovery prepare', 'Verify signed packages and prepare a portable unsigned input bundle', command='recovery-bundle', internal_action='prepare')
    p.add_argument('--packages', type=Path, required=True, help='Directory containing the exact downloaded RPM files')
    p.add_argument('--public-key', type=Path, required=True, help='Path to the independently trusted RPM signing public key')
    p.add_argument('--spec', type=Path, required=True, help='Path to an immutable candidate specification JSON file')
    p.add_argument('--output', type=Path, required=True, help='New output path; existing files are not overwritten')
    p.add_argument('--vendor-inventory', type=Path, help='reviewed inventory JSON for this exact signed RPM selection')
    p.add_argument('--builder-image', required=True, help='Exact local container image configuration ID (sha256:...)')
    p.add_argument('--epoch', type=int, required=True, help='Reproducible build timestamp in Unix seconds')
    p.add_argument('--free-space-reserve-gib', type=int, default=2, help='Free disk space to preserve during work, in GiB')
    p = action(root, 'dev recovery verify', 'Verify a portable input bundle and optional local builder', command='recovery-bundle', internal_action='verify')
    p.add_argument('bundle', type=Path, help='Directory containing a verified portable recovery input bundle')
    p.add_argument('--manifest-sha256', help='Expected SHA256 of the selected bundle manifest')
    p.add_argument('--engine', choices=('podman', 'docker'), help='Container engine to use for workers')
    p = action(root, 'dev recovery export', 'Copy verified inputs into a new portable directory', command='recovery-bundle', internal_action='export')
    p.add_argument('bundle', type=Path, help='Directory containing a verified portable recovery input bundle')
    p.add_argument('--output', type=Path, required=True, help='New output path; existing files are not overwritten')
    p.add_argument('--manifest-sha256', help='expected digest from the selected trusted snapshot')
    p.add_argument('--free-space-reserve-gib', type=int, default=2, help='Free disk space to preserve during work, in GiB')
    p = action(root, 'dev recovery import', 'Import a bundle matching an explicit trusted manifest digest', command='recovery-bundle', internal_action='import')
    p.add_argument('bundle', type=Path, help='Directory containing a verified portable recovery input bundle')
    p.add_argument('--output', type=Path, required=True, help='New output path; existing files are not overwritten')
    p.add_argument('--manifest-sha256', required=True, help='expected digest from the selected trusted snapshot')
    p.add_argument('--free-space-reserve-gib', type=int, default=2, help='Free disk space to preserve during work, in GiB')
    p = action(root, 'dev recovery build', 'Build an unsigned recovery image from a portable input bundle', command='recovery-bundle', internal_action='build')
    p.add_argument('bundle', type=Path, help='Directory containing a verified portable recovery input bundle')
    p.add_argument('--output', type=Path, required=True, help='New output path; existing files are not overwritten')
    p.add_argument('--manifest-sha256', help='Expected SHA256 of the selected bundle manifest')
    p.add_argument('--engine', choices=('podman', 'docker'), default='podman', help='Container engine to use for workers')
    p.add_argument('--cpus', type=int, help='Maximum worker CPUs within available capacity')
    p.add_argument('--memory-gib', type=int, help='Maximum worker memory in GiB')
    p.add_argument('--timeout', type=int, default=3600, help='Maximum operation duration in seconds')
    p.add_argument('--free-space-reserve-gib', type=int, default=2, help='Free disk space to preserve during work, in GiB')
    p = action(root, 'dev recovery submit', 'Submit recovery image production to the configured controller', command='recovery-image', internal_action=None)
    p.add_argument('--recipe', required=True, help='SHA256 of the exact retained recovery image recipe')
    p.add_argument('--builder-archive', required=True, help='SHA256 of the retained verified OCI builder archive')
    p.add_argument('--request-id', required=True, help='Durable request identity for safe retries')
    p = action(root, 'dev recovery build-recipe', 'Build an unsigned image from an exact retained recipe without a controller', command='recovery-image-build', internal_action=None)
    p.add_argument('--store', type=Path, required=True, help='existing CAS containing verified stock recipe and RPM inputs')
    p.add_argument('--recipe', required=True, help='SHA256 of the exact retained recovery image recipe')
    p.add_argument('--builder-image', required=True, help='exact local sha256 image configuration ID from the verified recipe')
    p.add_argument('--engine', choices=('podman', 'docker'), default='podman', help='Container engine to use for workers')
    p.add_argument('--podman-cgroup-manager', choices=['systemd', 'cgroupfs'], help='Explicit Podman resource manager override; otherwise use its configuration')
    p.add_argument('--output', type=Path, required=True, help='new output directory (checkout-local paths are allowed)')
    p.add_argument('--cpus', type=int, help='explicit CPU budget within effective capacity (default: interactive profile)')
    p.add_argument('--memory-gib', type=int, help='explicit GiB budget; default recovery profile is 4 GiB')
    p.add_argument('--timeout', type=int, default=3600, help='whole-container deadline in seconds')
    p.add_argument('--free-space-reserve-gib', type=int, default=2, help='free disk space retained during staging and in addition to image/temp capacity (default: 2 GiB)')
    p = action(root, 'dev recovery cleanup', 'Stop only the recorded foreground build container; preserve files', command='recovery-image-cleanup', internal_action=None)
    p.add_argument('output', type=Path, help='Existing foreground build directory containing the recorded container identity')
    p = action(root, 'dev recovery inputs replay-check', 'Check availability of exact retained RPM inputs', command='recovery-inputs', internal_action='replay-check')
    p.add_argument('--spec', type=Path, required=True, help='Path to an immutable candidate specification JSON file')
    p.add_argument('--directory', type=Path, required=True, help='Directory holding the selected input files')
    p = action(root, 'dev recovery inputs candidate-spec', 'Describe a reviewed candidate with explicitly selected repository bytes', command='recovery-inputs', internal_action='candidate-spec')
    p.add_argument('--candidate', choices=['fedora44-pairing-v1'], required=True, help='Reviewed candidate specification identity')
    p.add_argument('--repository', type=Path, required=True, help='reviewed .repo file for the exact selected closure')
    p.add_argument('--repository-id', action='append', required=True, help='enabled ID from supplied repository; repeat for each selected ID')
    p = action(root, 'dev recovery inputs acquire-plan', 'Prepare an exact package acquisition plan', command='recovery-inputs', internal_action='acquire-plan')
    p.add_argument('directory', type=Path, help='Directory holding the selected input files')
    p.add_argument('--spec', type=Path, help='immutable acquisition specification with pinned repository bytes and RPM trust')
    p = action(root, 'dev recovery inputs lock', 'Verify and retain the selected signed RPM packages', command='recovery-inputs', internal_action='lock')
    p.add_argument('directory', type=Path, help='Directory holding the selected input files')
    p.add_argument('--public-key', type=Path, required=True, help='Path to the independently trusted RPM signing public key')
    p.add_argument('--spec', type=Path, help='same immutable specification used for acquisition; otherwise retains legacy selection')
    p.add_argument('--vendor-inventory', type=Path, help='reviewed vendor inventory JSON for the exact RPM selection')
    p.add_argument('--builder-image-digest', required=True, help='Exact local container image configuration ID (sha256:...)')
    p.add_argument('--diagnostics', type=Path, required=True, help='Output directory for package verification diagnostics')
    p = action(root, 'dev recovery inputs recipe', 'Create an image recipe from an exact package lock', command='recovery-inputs', internal_action='recipe')
    p.add_argument('--lock', required=True, help='SHA256 of the retained exact RPM lock')
    p.add_argument('--builder-image-digest', required=True, help='Exact local container image configuration ID (sha256:...)')
    p.add_argument('--id', help='recipe identity; defaults to the selected lock digest')
    p.add_argument('--epoch', type=int, required=True, help='Reproducible build timestamp in Unix seconds')
    p.add_argument('--root-mib', type=int, default=2048, help='Recovery root filesystem size in MiB')
    p.add_argument('--factory-size-mib', type=int, default=4096, help='Compact factory image size in MiB')
    p.add_argument('--experiment-mib', type=int, default=32768, help='Experimental system partition size in MiB')
    p.add_argument('--library-mib', type=int, default=32768, help='Diagnostic library partition size in MiB')
    p.add_argument('--log-budget-mib', type=int, default=4096, help='Evidence log budget in MiB')
    p = action(root, 'dev image assemble', 'Assemble a new regular-file USB image', command='image', internal_action=None)
    p.add_argument('manifest', type=Path, help='Path to the image input manifest')
    p.add_argument('--reserve-gib',type=float,default=20,help='Free storage reserve in GiB')
    p = action(root, 'dev image qualify', 'Run gated UEFI qualification trials; requires an explicit release request', command='qualify-image', internal_action=None)
    p.add_argument('image', type=Path, help='Path to the regular-file image to qualify')
    p.add_argument('--manifest', type=Path, required=True, help='Path to the image input manifest')
    p.add_argument('--ovmf-code', type=Path, required=True, help='Path to the read-only UEFI firmware code image')
    p.add_argument('--ovmf-vars', type=Path, required=True, help='Path to the clean UEFI variable template')
    p.add_argument('--work', type=Path, required=True, help='New directory for qualification files and logs')
    p.add_argument('--timeout', type=int, default=180, help='Maximum operation duration in seconds')
    p = action(root, 'dev release check', 'Verify signed release inputs and report missing files', command='release-check', internal_action=None)
    p.add_argument('directory', type=Path, help='Directory holding the selected input files')
    p.add_argument('--inputs', type=Path, required=True, help='existing CAS root containing objects/SHA256')
    p.add_argument('--trust-bundle', type=Path, required=True, help='independently provisioned publisher trust')
    p.add_argument('--baseline', help='one exact supported identity; required for multiple catalog entries')
    p.add_argument('--timeout', type=int, default=300, help='bounded inspection seconds, at most 600')
