"""Target command arguments; services own behavior and authorization."""
from pathlib import Path
from .cli_parser import action


def build(root):
    p = action(root, 'target inventory', 'Inspect target hardware and missing candidate inputs', command='target-inventory', internal_action=None)
    p.add_argument('device_id', help='Target ID')
    p = action(root, 'target pair', 'Create a pairing invitation; confirm the fingerprint on the target', command='target', internal_action='add')
    p.add_argument('name', help='Target name or exact target ID')
    p.add_argument('--request-id', help='Durable request identity for safe retries')
    p.add_argument('--ttl-seconds', type=int, help='Invitation lifetime in seconds')
    p.set_defaults(replace=None, ttl_seconds=None, generation=None, new_name=None, new_uuid=None, file=None, grant=None, status_version=2)
    p = action(root, 'target show', 'Show target enrollment, contact and recovery facts', command='target', internal_action='show')
    p.add_argument('name', help='Target name or exact target ID')
    p.set_defaults(request_id=None)
    p.set_defaults(replace=None, ttl_seconds=None, generation=None, new_name=None, new_uuid=None, file=None, grant=None, status_version=2)
    p = action(root, 'target pairing cancel', 'Cancel an unused pairing invitation', command='target', internal_action='revoke-code')
    p.add_argument('name', help='Target name or exact target ID')
    p.add_argument('--request-id', help='Durable request identity for safe retries')
    p.set_defaults(replace=None, ttl_seconds=None, generation=None, new_name=None, new_uuid=None, file=None, grant=None, status_version=2)
    p = action(root, 'target access revoke', 'Revoke target credentials and pause its investigations', command='target', internal_action='revoke')
    p.add_argument('name', help='Target name or exact target ID')
    p.add_argument('--request-id', help='Durable request identity for safe retries')
    p.add_argument('--generation', help='exact credential generation expected by target revoke')
    p.set_defaults(replace=None, ttl_seconds=None, generation=None, new_name=None, new_uuid=None, file=None, grant=None, status_version=2)
    p = action(root, 'target reassign', 'Create an invitation to reassign a target identity', command='target', internal_action='retarget-code')
    p.add_argument('name', help='Target name or exact target ID')
    p.add_argument('--request-id', help='Durable request identity for safe retries')
    p.add_argument('--ttl-seconds', type=int, help='Invitation lifetime in seconds')
    p.add_argument('--generation', help='exact credential generation expected by target revoke')
    p.add_argument('--new-name', help='new enrollment name for an explicitly scoped retarget invitation')
    p.add_argument('--new-uuid', help='exact new SMBIOS system UUID for an explicitly scoped retarget invitation')
    p.set_defaults(replace=None, ttl_seconds=None, generation=None, new_name=None, new_uuid=None, file=None, grant=None, status_version=2)
    p = action(root, 'target evidence approve', 'Authorize upload of an exact original evidence manifest', command='target', internal_action='drain-approve')
    p.add_argument('name', help='Target name or exact target ID')
    p.add_argument('--request-id', help='Durable request identity for safe retries')
    p.add_argument('--ttl-seconds', type=int, help='Invitation lifetime in seconds')
    p.add_argument('--file', type=Path, help='exact original evidence manifest for explicit drain approval')
    p.set_defaults(replace=None, ttl_seconds=None, generation=None, new_name=None, new_uuid=None, file=None, grant=None, status_version=2)
    p = action(root, 'target evidence revoke', 'Revoke an evidence upload grant', command='target', internal_action='drain-revoke')
    p.add_argument('name', help='Target name or exact target ID')
    p.add_argument('--request-id', help='Durable request identity for safe retries')
    p.add_argument('--grant', help='exact old-evidence drain grant to revoke')
    p.set_defaults(replace=None, ttl_seconds=None, generation=None, new_name=None, new_uuid=None, file=None, grant=None, status_version=2)
    p = action(root, 'target shutdown request', 'Request safe shutdown and wait for target confirmation', command='target', internal_action='poweroff')
    p.add_argument('name', help='Target name or exact target ID')
    p.add_argument('--request-id', help='Durable request identity for safe retries')
    p.add_argument('--replace', help='explicit prior shutdown request to replace only after a reconciled changed boot')
    p.set_defaults(replace=None, ttl_seconds=None, generation=None, new_name=None, new_uuid=None, file=None, grant=None, status_version=2)
    p = action(root, 'target shutdown status', 'Show shutdown progress; physical poweroff needs local confirmation', command='target', internal_action='poweroff-status')
    p.add_argument('name', help='Target name or exact target ID')
    p.add_argument('--request-id', help='Durable request identity for safe retries')
    p.set_defaults(replace=None, ttl_seconds=None, generation=None, new_name=None, new_uuid=None, file=None, grant=None, status_version=2)
    p = action(root, 'target shutdown cancel', 'Cancel a shutdown request; investigations remain paused', command='target', internal_action='poweroff-cancel')
    p.add_argument('name', help='Target name or exact target ID')
    p.add_argument('--request-id', help='Durable request identity for safe retries')
    p.set_defaults(replace=None, ttl_seconds=None, generation=None, new_name=None, new_uuid=None, file=None, grant=None, status_version=2)
