"""Small adapter boundaries; contracts.py owns their versioned data models."""
from typing import Protocol
from .contracts import Artifact, CapabilityReport, Experiment, Progress, Result

class Builder(Protocol):
    def build(self, experiment: Experiment) -> dict[str, Artifact]: ...

class ArtifactRepository(Protocol):
    def put(self, raw: bytes, expected_digest: str | None = None) -> Artifact: ...
    def get(self, value: str) -> bytes: ...

class TargetTransport(Protocol):
    device_id: str
    def register(self, report: CapabilityReport) -> dict: ...
    def claim(self, boot_id: str, request_id: str) -> dict | None: ...
    def reconcile(self, boot_id: str) -> dict: ...
    def start(self, attempt_id: str, token: str, boot_id: str) -> dict: ...
    def heartbeat(self, attempt_id: str, token: str, boot_id: str) -> dict: ...
    def progress(self, attempt_id: str, token: str, report: Progress) -> dict: ...
    def artifact(self, digest: str) -> bytes: ...
    def upload(self, attempt_id: str, token: str, boot_id: str, upload_id: str, offset: int, data: bytes, expected_digest: str, total_size: int) -> dict: ...
    def evidence(self, attempt_id: str, token: str, stream: str, sequence: int, sha256_value: str, size: int) -> dict: ...
    def complete(self, result: Result, token: str, boot_id: str) -> dict: ...

class CodingAgent(Protocol):
    def decide(self, context: dict) -> dict: ...

# BootControl and RecipeOutput are defined alongside TargetAgent to avoid
# importing any boot implementation into the controller process.

from .target import BootControl, RecipeOutput

class RecipeRunner(Protocol):
    def __call__(self, experiment: Experiment) -> RecipeOutput: ...
